### PR TITLE
add classNameContainer function support

### PR DESCRIPTION
**Pull request by garbin**
In my use case, the child container has a className different root container, this feature can be used in this situtation. Hope this useful for other peoples:)

### CODE REVIEW

**Comment by alpertuna** [comment]
Thanks for your support :)
I have inspected the code and dynamic class names may be beneficial for some cases.
However, if your main purpose is changing root container's class name, you can do it by css selectors.

For example;
- to select root container; `.metismenu > .metismenu-container`
- and for child containers `.metismenu-container .metismenu-container`

**Comment by garbin** [comment]
thank you for your solution，I agree with it can done the same job，but if the css theme you use is too complecate to rewrite  or you have no permit to rewrite the css，this will be very useful.

**Comment by alpertuna** [comment]
Why did you close it, I would merge it :blush: There will be some updates, that's why I hold it.

**Comment by garbin** [comment]
Sorry, no any feedback, so I think you do not need this. reopen now :-)

**Comment by alpertuna** [comment]
It is open for any improvements, this is also an improvement :blush:

**Comment by alpertuna** [comment]
Manually merged and published as `v1.3.0-alpha.3` :ok_hand:. Sorry for late return :no_mouth:

**Comment by alpertuna** [comment]
And, I would like to note it, I have changed the `classNameContainer` function parameters.

Function is called like this;
```javascript
// Before; classContainer(itemId, visible, items);
classContainer({ itemId, visible, items });
```
Since people may be confused to remember parameter order.

**Pull request closed without merging**
