### PR TITLE
Add classNameSubmenuContainer & classNameItemHasVisibleChild for my use case

### PR DESCRIPTION
**Pull request by garbin**
Add classNameSubmenuContainer & classNameItemHasVisibleChild for http://modularcode.io/modular-admin-html case.
use lodash.isequal to avoiding unnecessary updateContent.

### CODE REVIEW

**Comment by alpertuna** [comment]
Hi @garbin,
Thanks for your contribute! I have reviewed your commit.

`classNameHasVisibleChild` prop may be useful for some cases. :+1:

However `classNameSubMenuContainer` prop looks a little unnecessary. Because there is a way to style submenu containers. To achive this, for example `classNameContainer` has `container` css class. You can use this css structure;
```css
.container .container{
...
}
```
to style submenu containers.

Lastly, `loadash.isequal` approach will cause performance loses. Because it compares full depth of object. When you manage props correctly, it already won't fire update methods. If something causes unnecessary updates, and you put `isequal` check to achive, it means that `isequal` will work for each render. And as I mention before it causes performance loses.

Now, It checks just reference of content object. If there is unnecessary update in your application, object reference must be changed or object is being created again. To avoid this, you should move your content object assignment outside of `render` or other functions that works repeatedly, even outside of that component class.

Shortly be sure not to change object reference to avoid unnecessary updates.
Nonetheless, if you cant achive this and `isequal` check is really needed, I will accept your fix :blush: I will be waiting your feedback about this case.

**Comment by garbin** [comment]
Thank you for yout detailed review. agree with yout about `classNameSubMenuContainer` and agree with you about `lodash.isequal` too,  But...

here is my code
```js
const menu = [];
class Menu extends React.Component {
   render(){
      return <div><MetisMenu content={menu} ... /></div>
   }
}
```

I can't figure out what's wrong with this code, menu is a const variable, so it can not be re-assign. So I think is a bug and make a PR to fix this because updateContent always be called after link item being clicked. any idea?

BTW: I use react-metismenu-router-link too.

**Comment by alpertuna** [comment]
I looked into it and tried it with `react-metismenu-router-link` and `updateContent` is not fired again as expected.
Maybe in your application whole menu component is created repeatedly, and it causes `constructor` method work more than once. Actually in this case `loadash` wouldn't be solution again.

**Comment by alpertuna** [comment]
Also revert commit, thanks :blush: I will publish this patch soon

**Comment by alpertuna** [comment]
I have published your commit to npm repos, sorry for late publish.
If you didn't find any solution for your case and `loadash` solves it, still you can open issue or send PR, I will accept it.

**Comment by garbin** [comment]
@alpertuna Thank you! You are so reliable! That problem has been solved, It causes by my mistake... a typo... sorry for not give you a feedback about this.

**Comment by alpertuna** [comment]
Then no problem :blush:

**Pull request merged**
